import { generateKeyPair, sign } from '../crypto/index.js'
import { bytesToHex, publicKeyText } from '../lift/digest.js'
import { digest } from './functions.js'

/**
 * Keys, signatures and party identity, in the text forms the schema stores.
 *
 * Hex throughout, because `src/lift/digest.ts` already fixes that as "the schema's text
 * form". A second encoding would mean the same key is two different strings depending on
 * which path wrote it -- the same failure as a second digest, and just as quiet.
 */

const utf8 = new TextEncoder()

/** A key pair with its public half in the schema's text form. */
export interface KeyPairText {
	publicKey: string
	secretKey: Uint8Array
}

/** Sign a digest with a party's key, in the hex form the schema stores. */
export function signText(key: KeyPairText, digestText: string): string {
	return bytesToHex(sign(key.secretKey, utf8.encode(digestText)))
}

export function newKey(): KeyPairText {
	const pair = generateKeyPair()
	return { publicKey: publicKeyText(pair.publicKey), secretKey: pair.secretKey }
}

/** An invitation key: generated by the inviter, its secret half shared out of band. */
export function newInvitation(): { publicKey: string; secretKey: Uint8Array } {
	return newKey()
}

/**
 * A party identity: the content address of its genesis key.
 *
 * `docs/architecture.md` says a Sid *is* "the hash of the genesis (Revision 1) public key".
 * Nothing in the schema holds anyone to that today -- see `test/STATUS.md` § 0 -- so this is
 * the rule stated in one place, ready for the constraint when it lands.
 */
export function sidFor(genesisPublicKey: string): string {
	return `sid:${digest(genesisPublicKey)}`
}
