import { generateKeyPair, sign } from '../crypto/index.js'
import { fromText, publicKeyText, toText } from '../lift/digest.js'
import { digest } from './functions.js'

/**
 * Keys, signatures and party identity, in the text forms the schema stores.
 *
 * base64url throughout -- `toText` in `src/lift/digest.ts` -- because it is what the stack's
 * `digest` emits and its `verify` decodes. A second encoding would mean the same key is two
 * different strings depending on which path wrote it, and just as quiet a failure as a second
 * digest.
 */

/** A key pair with its public half in the schema's text form. */
export interface KeyPairText {
	publicKey: string
	secretKey: Uint8Array
}

/**
 * Sign a digest with a party's key, in the text form the schema stores.
 *
 * What is signed is the digest's **raw bytes**, not its text: the schema checks with
 * `verify(digest(...), Signature, Key, 'ed25519')`, and the plugin's `verify` decodes the
 * digest text back to bytes before checking. Signing the text instead would produce a
 * signature every replica refuses.
 */
export function signText(key: KeyPairText, digestText: string): string {
	return toText(sign(key.secretKey, fromText(digestText)))
}

export function newKey(): KeyPairText {
	const pair = generateKeyPair()
	return { publicKey: publicKeyText(pair.publicKey), secretKey: pair.secretKey }
}

/** An invitation key: generated by the inviter, its secret half shared out of band. */
export function newInvitation(): { publicKey: string; secretKey: Uint8Array } {
	return newKey()
}

/**
 * A party identity: the content address of its genesis key.
 *
 * `docs/architecture.md` says a Sid *is* "the hash of the genesis (Revision 1) public key".
 * Nothing in the schema holds anyone to that today -- see `test/STATUS.md` § 0 -- so this is
 * the rule stated in one place, ready for the constraint when it lands.
 */
export function sidFor(genesisPublicKey: string): string {
	return `sid:${digest(genesisPublicKey)}`
}
